# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_recorder.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1182, 323)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1160, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3_1.setEnabled(True)
        self.label_3_1.setAutoFillBackground(False)
        self.label_3_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_3_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3_1.setLineWidth(1)
        self.label_3_1.setText("")
        self.label_3_1.setOpenExternalLinks(False)
        self.label_3_1.setObjectName("label_3_1")
        self.verticalLayout.addWidget(self.label_3_1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_4_1.setText("")
        self.label_4_1.setObjectName("label_4_1")
        self.verticalLayout_2.addWidget(self.label_4_1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_5_1.setText("")
        self.label_5_1.setObjectName("label_5_1")
        self.verticalLayout_3.addWidget(self.label_5_1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_6_1.setText("")
        self.label_6_1.setObjectName("label_6_1")
        self.verticalLayout_4.addWidget(self.label_6_1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_7_1.setText("")
        self.label_7_1.setObjectName("label_7_1")
        self.verticalLayout_5.addWidget(self.label_7_1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_8_1.setText("")
        self.label_8_1.setObjectName("label_8_1")
        self.verticalLayout_6.addWidget(self.label_8_1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_9_1.setText("")
        self.label_9_1.setObjectName("label_9_1")
        self.verticalLayout_7.addWidget(self.label_9_1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_10_1.setText("")
        self.label_10_1.setObjectName("label_10_1")
        self.verticalLayout_8.addWidget(self.label_10_1)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_j_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_j_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_j_1.setText("")
        self.label_j_1.setObjectName("label_j_1")
        self.verticalLayout_10.addWidget(self.label_j_1)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_q_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_q_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_q_1.setText("")
        self.label_q_1.setObjectName("label_q_1")
        self.verticalLayout_11.addWidget(self.label_q_1)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_k_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_k_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_k_1.setText("")
        self.label_k_1.setObjectName("label_k_1")
        self.verticalLayout_13.addWidget(self.label_k_1)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_a_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_a_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_a_1.setText("")
        self.label_a_1.setObjectName("label_a_1")
        self.verticalLayout_12.addWidget(self.label_a_1)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2_1.setStyleSheet("image: url(:/cards/timg.jpeg);")
        self.label_2_1.setText("")
        self.label_2_1.setObjectName("label_2_1")
        self.verticalLayout_9.addWidget(self.label_2_1)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 1160, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3_2.setStyleSheet("")
        self.label_3_2.setText("")
        self.label_3_2.setObjectName("label_3_2")
        self.horizontalLayout_2.addWidget(self.label_3_2)
        self.label_4_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4_2.setStyleSheet("")
        self.label_4_2.setText("")
        self.label_4_2.setObjectName("label_4_2")
        self.horizontalLayout_2.addWidget(self.label_4_2)
        self.label_5_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5_2.setStyleSheet("")
        self.label_5_2.setText("")
        self.label_5_2.setObjectName("label_5_2")
        self.horizontalLayout_2.addWidget(self.label_5_2)
        self.label_6_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6_2.setStyleSheet("")
        self.label_6_2.setText("")
        self.label_6_2.setObjectName("label_6_2")
        self.horizontalLayout_2.addWidget(self.label_6_2)
        self.label_7_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7_2.setStyleSheet("")
        self.label_7_2.setText("")
        self.label_7_2.setObjectName("label_7_2")
        self.horizontalLayout_2.addWidget(self.label_7_2)
        self.label_8_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8_2.setStyleSheet("")
        self.label_8_2.setText("")
        self.label_8_2.setObjectName("label_8_2")
        self.horizontalLayout_2.addWidget(self.label_8_2)
        self.label_9_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9_2.setStyleSheet("")
        self.label_9_2.setText("")
        self.label_9_2.setObjectName("label_9_2")
        self.horizontalLayout_2.addWidget(self.label_9_2)
        self.label_10_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10_2.setStyleSheet("")
        self.label_10_2.setText("")
        self.label_10_2.setObjectName("label_10_2")
        self.horizontalLayout_2.addWidget(self.label_10_2)
        self.label_j_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_j_2.setStyleSheet("")
        self.label_j_2.setText("")
        self.label_j_2.setObjectName("label_j_2")
        self.horizontalLayout_2.addWidget(self.label_j_2)
        self.label_q_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_q_2.setStyleSheet("")
        self.label_q_2.setText("")
        self.label_q_2.setObjectName("label_q_2")
        self.horizontalLayout_2.addWidget(self.label_q_2)
        self.label_k_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_k_2.setStyleSheet("")
        self.label_k_2.setText("")
        self.label_k_2.setObjectName("label_k_2")
        self.horizontalLayout_2.addWidget(self.label_k_2)
        self.label_a_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_a_2.setStyleSheet("")
        self.label_a_2.setText("")
        self.label_a_2.setObjectName("label_a_2")
        self.horizontalLayout_2.addWidget(self.label_a_2)
        self.label_2_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2_2.setStyleSheet("")
        self.label_2_2.setText("")
        self.label_2_2.setObjectName("label_2_2")
        self.horizontalLayout_2.addWidget(self.label_2_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 1160, 131))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3_3.setStyleSheet("")
        self.label_3_3.setText("")
        self.label_3_3.setObjectName("label_3_3")
        self.horizontalLayout_4.addWidget(self.label_3_3)
        self.label_4_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4_3.setStyleSheet("")
        self.label_4_3.setText("")
        self.label_4_3.setObjectName("label_4_3")
        self.horizontalLayout_4.addWidget(self.label_4_3)
        self.label_5_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_5_3.setStyleSheet("")
        self.label_5_3.setText("")
        self.label_5_3.setObjectName("label_5_3")
        self.horizontalLayout_4.addWidget(self.label_5_3)
        self.label_6_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6_3.setStyleSheet("")
        self.label_6_3.setText("")
        self.label_6_3.setObjectName("label_6_3")
        self.horizontalLayout_4.addWidget(self.label_6_3)
        self.label_7_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_7_3.setStyleSheet("")
        self.label_7_3.setText("")
        self.label_7_3.setObjectName("label_7_3")
        self.horizontalLayout_4.addWidget(self.label_7_3)
        self.label_8_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8_3.setStyleSheet("")
        self.label_8_3.setText("")
        self.label_8_3.setObjectName("label_8_3")
        self.horizontalLayout_4.addWidget(self.label_8_3)
        self.label_9_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9_3.setStyleSheet("")
        self.label_9_3.setText("")
        self.label_9_3.setObjectName("label_9_3")
        self.horizontalLayout_4.addWidget(self.label_9_3)
        self.label_10_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_10_3.setStyleSheet("")
        self.label_10_3.setText("")
        self.label_10_3.setObjectName("label_10_3")
        self.horizontalLayout_4.addWidget(self.label_10_3)
        self.label_j_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_j_3.setStyleSheet("")
        self.label_j_3.setText("")
        self.label_j_3.setObjectName("label_j_3")
        self.horizontalLayout_4.addWidget(self.label_j_3)
        self.label_q_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_q_3.setStyleSheet("")
        self.label_q_3.setText("")
        self.label_q_3.setObjectName("label_q_3")
        self.horizontalLayout_4.addWidget(self.label_q_3)
        self.label_k_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_k_3.setStyleSheet("")
        self.label_k_3.setText("")
        self.label_k_3.setObjectName("label_k_3")
        self.horizontalLayout_4.addWidget(self.label_k_3)
        self.label_a_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_a_3.setStyleSheet("")
        self.label_a_3.setText("")
        self.label_a_3.setObjectName("label_a_3")
        self.horizontalLayout_4.addWidget(self.label_a_3)
        self.label_2_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2_3.setStyleSheet("")
        self.label_2_3.setText("")
        self.label_2_3.setObjectName("label_2_3")
        self.horizontalLayout_4.addWidget(self.label_2_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 110, 1161, 131))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_3_4.setStyleSheet("")
        self.label_3_4.setText("")
        self.label_3_4.setObjectName("label_3_4")
        self.horizontalLayout_5.addWidget(self.label_3_4)
        self.label_4_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4_4.setStyleSheet("")
        self.label_4_4.setText("")
        self.label_4_4.setObjectName("label_4_4")
        self.horizontalLayout_5.addWidget(self.label_4_4)
        self.label_5_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5_4.setStyleSheet("")
        self.label_5_4.setText("")
        self.label_5_4.setObjectName("label_5_4")
        self.horizontalLayout_5.addWidget(self.label_5_4)
        self.label_6_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6_4.setStyleSheet("")
        self.label_6_4.setText("")
        self.label_6_4.setObjectName("label_6_4")
        self.horizontalLayout_5.addWidget(self.label_6_4)
        self.label_7_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_7_4.setStyleSheet("")
        self.label_7_4.setText("")
        self.label_7_4.setObjectName("label_7_4")
        self.horizontalLayout_5.addWidget(self.label_7_4)
        self.label_8_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8_4.setStyleSheet("")
        self.label_8_4.setText("")
        self.label_8_4.setObjectName("label_8_4")
        self.horizontalLayout_5.addWidget(self.label_8_4)
        self.label_9_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_9_4.setStyleSheet("")
        self.label_9_4.setText("")
        self.label_9_4.setObjectName("label_9_4")
        self.horizontalLayout_5.addWidget(self.label_9_4)
        self.label_10_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_10_4.setStyleSheet("")
        self.label_10_4.setText("")
        self.label_10_4.setObjectName("label_10_4")
        self.horizontalLayout_5.addWidget(self.label_10_4)
        self.label_j_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_j_4.setStyleSheet("")
        self.label_j_4.setText("")
        self.label_j_4.setObjectName("label_j_4")
        self.horizontalLayout_5.addWidget(self.label_j_4)
        self.label_q_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_q_4.setStyleSheet("")
        self.label_q_4.setText("")
        self.label_q_4.setObjectName("label_q_4")
        self.horizontalLayout_5.addWidget(self.label_q_4)
        self.label_k_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_k_4.setStyleSheet("")
        self.label_k_4.setText("")
        self.label_k_4.setObjectName("label_k_4")
        self.horizontalLayout_5.addWidget(self.label_k_4)
        self.label_a_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_a_4.setStyleSheet("")
        self.label_a_4.setText("")
        self.label_a_4.setObjectName("label_a_4")
        self.horizontalLayout_5.addWidget(self.label_a_4)
        self.label_2_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2_4.setStyleSheet("")
        self.label_2_4.setText("")
        self.label_2_4.setObjectName("label_2_4")
        self.horizontalLayout_5.addWidget(self.label_2_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 55, 31))
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 250, 55, 31))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setLineWidth(0)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 250, 55, 31))
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(0)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 250, 55, 31))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(0)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 250, 55, 31))
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.label_j = QtWidgets.QLabel(self.centralwidget)
        self.label_j.setGeometry(QtCore.QRect(730, 250, 55, 31))
        self.label_j.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_j.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_j.setLineWidth(0)
        self.label_j.setObjectName("label_j")
        self.label_q = QtWidgets.QLabel(self.centralwidget)
        self.label_q.setGeometry(QtCore.QRect(820, 250, 55, 31))
        self.label_q.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_q.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_q.setLineWidth(0)
        self.label_q.setObjectName("label_q")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 250, 55, 31))
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setLineWidth(0)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(640, 250, 55, 31))
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setLineWidth(0)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 250, 55, 31))
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setLineWidth(0)
        self.label_8.setObjectName("label_8")
        self.label_a = QtWidgets.QLabel(self.centralwidget)
        self.label_a.setGeometry(QtCore.QRect(1000, 250, 55, 31))
        self.label_a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_a.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_a.setLineWidth(0)
        self.label_a.setObjectName("label_a")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1090, 250, 55, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.label_k = QtWidgets.QLabel(self.centralwidget)
        self.label_k.setGeometry(QtCore.QRect(910, 250, 55, 31))
        self.label_k.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_k.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_k.setLineWidth(0)
        self.label_k.setObjectName("label_k")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.statusbar.showMessage("No card detected!")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Card Recorder"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_j.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_q.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_a.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))
        self.label_k.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">4</span></p></body></html>"))

import puke_rc
